### ISSUE TITLE
Zip downloads are empty sometimes.

### ISSUE THREAD

**Issue by Foxcapades** [VEuPathDB/service-multi-blast#102]
Rather than returning an error, it successfully returns the zip with no content.

**Comment by Foxcapades** [comment]
```
/out/c4707746854e919dd37daa9dec92a507/441631eb6b01237378089d4565e1e7a5:
total 138448
-rw-r--r--    1 root     root     141759463 Apr  5 12:44 report.txt
-rw-r--r--    1 root     root            24 Apr  5 12:44 meta.json
-rw-r--r--    1 root     root            22 Apr  5 12:44 report.zip
```

**Comment by Foxcapades** [comment]
May be a weird race condition where the report.txt file does not yet exist but the formatter command has completed

**Comment by Foxcapades** [comment]
May be resolved by busy-waiting for the report file to exist before zipping the directory.

**Comment by aurreco-uga** [comment]
interesting : the meta.json only has the zip file, missing the txt file.. 
this breaks the download..  (the client would be requesting the txt file if available)
