### ISSUE TITLE
MultiBLAST: Sequence with spaces at the start of lines results in an unrelated/invalid error message.

### ISSUE THREAD

**Issue by Foxcapades** [VEuPathDB/service-multi-blast#104]

**Comment by aurreco-uga** [comment]
![image](https://user-images.githubusercontent.com/16354313/156239708-666143b2-8635-4e1d-b4fc-a9e9a3f4774c.png)

**Comment by aurreco-uga** [comment]
tested in qa.toxo
![Screen Shot 2022-03-07 at 1 58 24 PM](https://user-images.githubusercontent.com/16354313/157100392-325fc519-d18d-4d9a-95aa-f6b0522067c1.png)

**Comment by Foxcapades** [comment]
Fix on QA

**Comment by aurreco-uga** [comment]
just tested in qa.plasmo and i got the error:
<img width="1323" alt="Screen Shot 2022-04-01 at 2 59 28 PM" src="https://user-images.githubusercontent.com/16354313/161325444-31ebb5d4-678d-4d7d-87f5-41549bc679b7.png">

**Comment by aurreco-uga** [comment]
here is a sequence
[sequence-with-spaces.txt](https://github.com/VEuPathDB/service-multi-blast/files/8400372/sequence-with-spaces.txt)
