### ISSUE TITLE
Multiple identical multi-sequence jobs created and run.

### ISSUE THREAD

**Issue by Foxcapades** [VEuPathDB/service-multi-blast#117]
When a multi-sequence job is created, it appears that a job is created for each sequence sometimes?  Unclear.

Hash is based on the short sequence, but somehow, sometimes it appears that the full query is written to query.txt.

[2EDE1A9_old.txt](https://github.com/VEuPathDB/service-multi-blast/files/8209218/2EDE1A9_old.txt)

Compare to the query in the database.

**Comment by aurreco-uga** [comment]
as i commented in #119 i think this got fixed with my commit fixing a bug by which the client was submitting a different param value..
