### ISSUE TITLE
Return formatter errors to the client when a config fails validation.

### ISSUE THREAD

**Issue by Foxcapades** [VEuPathDB/service-multi-blast#127]

**Comment by Foxcapades** [comment]
Relates to #122

**Comment by aurreco-uga** [comment]
not sure these are formatter or blast run errors that show in the formatter logs..

**Comment by Foxcapades** [comment]
The formatter logs only include errors/messages from the formatter and it's wrapping server

**Comment by Foxcapades** [comment]
The error log should be written to file so it can be retrieved from the blast service.

**Comment by Foxcapades** [comment]
This is handled by the rewrite.
