### ISSUE TITLE
2 database related   500 database errors:  make 400 and ignore, respectively

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/service-multi-blast#147]
these are 2 other 500 errors we see occasionally

Caused by: java.sql.SQLIntegrityConstraintViolationException: ORA-01400: cannot insert NULL into ("USERLOGINS5"."MULTIBLAST_JOBS"."QUERY")

 a way to reproduce this one is by entering a blast sequence like:
>def

**This should become a user error, a 400 with a nicer message**. 

--------------------
Caused by: java.sql.SQLIntegrityConstraintViolationException: ORA-00001: unique constraint (USERLOGINS5.MB_UQ_USER_JOB) violated

seems like a race condition
the constraint mb_uq_user_job  is in multiblast_users
see (https://github.com/VEuPathDB/service-multi-blast/blob/master/databases/wdk/user-tables.sql)
  CONSTRAINT mb_uq_user_job

the error means that it's trying to insert a link from a user to a job that already exists
ellie says:  so the error doesn't cause any problems, except for the 500

**unless i am missing something I would ignore this situation and not throw the 500.. since it is harmless...**

**Comment by Foxcapades** [comment]
Part one of this ticket has a fix merged and tagged as 1.7.17

**Comment by Foxcapades** [comment]
Issue 2 stacktrace: [stactrace.txt](https://github.com/VEuPathDB/service-multi-blast/files/9122555/stactrace.txt)
