### ISSUE TITLE
mblast: when logging in, the existing guest jobs description field does not get copied

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/service-multi-blast#148]

**Comment by Foxcapades** [comment]
This needs to be confirmed.  I suspect this will have been resolved by a [previous fix](https://github.com/VEuPathDB/service-multi-blast/commit/c0588c786c8e851a9b9c90ad948b761998d993a0) to the guest user linking process that went out in 1.7.16

Closing for now.
