### ISSUE TITLE
Fail gracefully on jobs failing due to age (build #)

### ISSUE THREAD

**Issue by Foxcapades** [VEuPathDB/service-multi-blast#82]
**Scenario**:

. User submits a blast job when the site is on build-50
. User comes back and attempts to rerun job when site is now on build-52
. User gets a job failure with no explanation

**Resolution**:

We need, at the bare minimum, some way of detecting this error (before it happens?) so we can report back a useful message about why a job can no longer be run.

Optionally, in the future, we can offer a way to 'upgrade' the job to point to the more up to date blast targets?

**Comment by aurreco-uga** [comment]
we had a fut recently about this and decided to not store teh build# in teh config, so we might want to close this issue..
