### ISSUE TITLE
query sequence should allow spaces and numbers as in https://www.ncbi.nlm.nih.gov/protein/1790350

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/service-multi-blast#84]
the query sequence should allow spaces…and should be stripped out like a newline or an empty line

**Comment by aurreco-uga** [comment]
the query sequence should allow spaces…and should be stripped out like a newline or an empty line

**Comment by Foxcapades** [comment]
Relates to #91 and #104

**Comment by aurreco-uga** [comment]
i skipped validating spaces
https://github.com/VEuPathDB/service-multi-blast/commit/137692d28b2b2aa5d4d4bfacd1f7ebe3a670544d
and it works, the query in teh result sshows without spaces though.. possibly part of the hash generation which was removing empty lines..

will patch qa and close this issue.

**Comment by aurreco-uga** [comment]
we need t

**Comment by aurreco-uga** [comment]
we need to enable also numbers as in
https://www.ncbi.nlm.nih.gov/protein/1790350

**Comment by Foxcapades** [comment]
This should already be fixed?
